[project]

name = "{{cookiecutter.project_name}}"
version = "1.0.0"
description = "{{cookiecutter.description}}"
authors = [
  {name = "Flet Developer", email = "your@email.com"}
]
dependencies = ["flet=={{cookiecutter.flet_version}}"]