{%- if cookiecutter.package_manager != "poetry" -%}
[project]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.description}}"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "flet=={{cookiecutter.flet_version}}"
]
{% else %}
[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.1.0"
description = "{{cookiecutter.description}}"
authors = ["Flet Developer <your@email.com>"]
readme = "README.md"
{% endif %}

[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.mycompany"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "{{cookiecutter.project_name}}"

# company name to display in about app dialogs
company = "My Company"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2024 by MyCompany"

[tool.flet.app]
path = "src"

{%- if cookiecutter.package_manager == "uv" %}

[tool.uv]
dev-dependencies = [
    "flet[all]=={{cookiecutter.flet_version}}",
]
{%- elif cookiecutter.package_manager == "poetry" %}

[tool.poetry.dependencies]
python = "^3.8"
flet = {version = "{{cookiecutter.flet_version}}"}

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "{{cookiecutter.flet_version}}"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
{% endif %}